#Create DataBase
#key : "Value"
version : "3"
services: 
  db: 
    image: postgres:latest
    container_name: "Nat-DB"
    ports:
      #external:internal
      - 54321:5432
    environment:
      #only in Drive Lv2 Protect
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}