#Create DataBase
#key : "Value"
version : "3"
services: 
  DB: 
    image: postgres:latest
    container_name: "Nat-DB"
    ports:
      #external:internal
      - 54321:5432
    environment:
      #only in Drive Lv2 Protect
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  pgAdmin:
    image: dpage/pgadmin4:14
    container_name: pgAdmin
    ports:
      - 4433:443
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  strapi:
    image: naskio/strapi:latest
    container_name: MyApp
    ports:
      - 1337:1337
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_CLIENT=postgres
      - DATABASE_SSL=false